---
kind: Service
apiVersion: v1
metadata:
  name: truckmanager-web-service
spec:
  selector:
    app: truckamanger
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 3001
      targetPort: 3000
      nodePort: 30003
  type: LoadBalancer


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: truckmanger-web-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: truckmanger
    spec:
      containers:
        - name: truckmanager
          image: eskilsand/truckmanager.web
          ports:
            - containerPort: 3000